name: Push project build to JFrog Artifactory and PyPI

on:
  workflow_dispatch:
    inputs:
      branch_to_build:
        description: 'Specify the branch you want to build'
        required: false
        default: $GITHUB_REF
      version_to_build:
        description: 'Specify the version you want to build: use SEMVER format only'
        required: false
        default: "0.0.0.dev"
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      # Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry, build, and publish via tag
        env:
          ARTIFACTORY_USERNAME: ${{ vars.JFROG_USER }}
          ARTIFACTORY_API_KEY: ${{ secrets.JFROG_API_KEY}}
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_KEY }}
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          pip install poetry
          poetry self add poetry-version-plugin
          git fetch --all --tags
          latesttag=$(git describe --tags $(git rev-list --tags --max-count=1))
          git checkout ${latesttag}
          make deploy

      - name: Install poetry, build, and publish via custom branch
        env:
          ARTIFACTORY_USERNAME: ${{ vars.JFROG_USER }}
          ARTIFACTORY_API_KEY: ${{ secrets.JFROG_API_KEY}}
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_KEY }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          pip install poetry
          poetry self add poetry-version-plugin
          git fetch --all
          git checkout ${{ github.event.inputs.branch_to_build }}
          git tag ${{ github.event.inputs.version_to_build }}
          make deploy
